# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6cf0dcd54e6c83f9c9aebda5f9708034795b1dae4b4880d06eb9cc753be3f9e4f90bd81742b47268c7b71f59ab7196eb2fddcc5baebcc5c30cb16cb9ef62e47

test:
  secret_key_base: 663403b99f3b2e66d10f34e5ea4f06658342937ce3bd9f587c208f43cc7baf1bd9b206c3858e90c7ce71d153c91cf86ede06c5f7c60242f433ebe57d34e6b062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
